### ISSUE TITLE
Create XlsxStreamer

### ISSUE THREAD

**Issue by TiagoJacobs** [iMDT/xlsx-io#3]
Create a class that read's a XLSX file and call a callBack with the methods:

onBegin
onRow
onEnd

**Comment by Klauswk** [comment]
Created on commit 521eceeb4aeeb507ec1cd6dd79497b3bd26e2da2 , the file can be find [here](https://github.com/iMDT/xlsx-io/blob/521eceeb4aeeb507ec1cd6dd79497b3bd26e2da2/src/main/java/br/com/imdt/xlsx/io/DataCallback.java)
